name: Chris A. Iradukunda
url: https://daqhris.com
enforce_ssl: daqhris.com
permalink: /404.html
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
  css_class: 'highlight'  
gems:
  - jekyll-sitemap
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
